 <script type="text/javascript">
var defaultCode="//Plese write code here";
	defaultCode=defaultCode+"\nimport java.util.*;";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	public class Main {";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	    private static String findClassHeld(int students ,int threshold,int[] arrivalTimes){";
	defaultCode=defaultCode+"\n	         //Write your code here";
	defaultCode=defaultCode+"\n	         return \"NO\";";
	defaultCode=defaultCode+"\n	    }          ";
	defaultCode=defaultCode+"\n	      ";
	defaultCode=defaultCode+"\n	    public static void main(String[] args) throws Exception {";
	defaultCode=defaultCode+"\n	            Scanner scan=new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            //user input for given students";
	defaultCode=defaultCode+"\n	            int students=scan.nextInt();";
	defaultCode=defaultCode+"\n	            int threshold=scan.nextInt();";
	defaultCode=defaultCode+"\n	            Scanner in = new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            String line=in.nextLine();";
	defaultCode=defaultCode+"\n	            String[] numsstring=line.split(\"[ ]+\");";
	defaultCode=defaultCode+"\n	            int arrivalTimes[]=new int[numsstring.length];";
	defaultCode=defaultCode+"\n	            int count=0;";
	defaultCode=defaultCode+"\n	            for(String s:numsstring){";
	defaultCode=defaultCode+"\n	            	arrivalTimes[count++]=Integer.parseInt(s);";
	defaultCode=defaultCode+"\n	            }";
	defaultCode=defaultCode+"\n	            String result=saveThePrisoner(students,threshold,arrivalTimes);";
	defaultCode=defaultCode+"\n	            System.out.println(result);";
	defaultCode=defaultCode+"\n	       ";
	defaultCode=defaultCode+"\n	      }";
	defaultCode=defaultCode+"\n	}";
	editor.setValue(defaultCode);
	editor.getSelection().clearSelection();
</script>	