 <script type="text/javascript">
var defaultCode="//Plese write code here";
	defaultCode=defaultCode+"\nimport java.util.*;";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	public class Main {";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	    private static int coinChange(int[] coins, int total){";
	defaultCode=defaultCode+"\n	         //Write your code here";
	defaultCode=defaultCode+"\n	         return 0;";
	defaultCode=defaultCode+"\n	    }          ";
	defaultCode=defaultCode+"\n	      ";
	defaultCode=defaultCode+"\n	    public static void main(String[] args) throws Exception {";
	defaultCode=defaultCode+"\n	            // Your code here!";
	defaultCode=defaultCode+"\n	            Scanner in = new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            String line=in.nextLine();";
	defaultCode=defaultCode+"\n	            String[] numsstring=line.split(\"[ ]+\");";
	defaultCode=defaultCode+"\n	            int coins []=new int[numsstring.length];";
	defaultCode=defaultCode+"\n	            int count=0;";
	defaultCode=defaultCode+"\n	            for(String s:numsstring){";
	defaultCode=defaultCode+"\n	            	coins [count++]=Integer.parseInt(s);";
	defaultCode=defaultCode+"\n	            }";
	defaultCode=defaultCode+"\n	            // Taking total as input!";
	defaultCode=defaultCode+"\n	            Scanner scan = new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            int total = scan.nextInt();";
	defaultCode=defaultCode+"\n	            int result=coinChange(coins ,total);";
	defaultCode=defaultCode+"\n	            System.out.println(result);";
	defaultCode=defaultCode+"\n	       ";
	defaultCode=defaultCode+"\n	      }";
	defaultCode=defaultCode+"\n	}";
	editor.setValue(defaultCode);
	editor.getSelection().clearSelection();
</script>	