 <script type="text/javascript">
var defaultCode="//Plese write code here";
	defaultCode=defaultCode+"\nimport java.util.*;";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	public class Main {";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	     /**";
	defaultCode=defaultCode+"\n	     * ";
	defaultCode=defaultCode+"\n	      * @param substring string to be searched";
	defaultCode=defaultCode+"\n	      * @param str source string";
	defaultCode=defaultCode+"\n	      * @return frequency of searched string";
	defaultCode=defaultCode+"\n	      */";
	defaultCode=defaultCode+"\n	     private static int countStringOccurrence(String substring,String str[]){";
	defaultCode=defaultCode+"\n	         //Write your code here";
	defaultCode=defaultCode+"\n	         return 0;";
	defaultCode=defaultCode+"\n	    }          ";
	defaultCode=defaultCode+"\n	      ";
	defaultCode=defaultCode+"\n	    public static void main(String[] args) throws Exception {";
	defaultCode=defaultCode+"\n	            // Your code here!";
	defaultCode=defaultCode+"\n	            Scanner scan=new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            String input=scan.nextLine();";
	defaultCode=defaultCode+"\n	            String sstring=scan.nextLine();";
	defaultCode=defaultCode+"\n	            String[] strarr=input.split(\"[ ]+\");";
	defaultCode=defaultCode+"\n	            int result=countStringOccurrence(sstring,strarr);";
	defaultCode=defaultCode+"\n	            System.out.println(result);";
	defaultCode=defaultCode+"\n	       ";
	defaultCode=defaultCode+"\n	      }";
	defaultCode=defaultCode+"\n	}";
	editor.setValue(defaultCode);
	editor.getSelection().clearSelection();
</script>	