 <script type="text/javascript">
var defaultCode="//Plese write code here";
	defaultCode=defaultCode+"\nimport java.util.*;";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	public class Main {";
	defaultCode=defaultCode+"\n";
	defaultCode=defaultCode+"\n	    private static boolean isNStraightHand(int[] hand, int w){";
	defaultCode=defaultCode+"\n	         //Write your code here";
	defaultCode=defaultCode+"\n	         return false;";
	defaultCode=defaultCode+"\n	    }          ";
	defaultCode=defaultCode+"\n	      ";
	defaultCode=defaultCode+"\n	    public static void main(String[] args) throws Exception {";
	defaultCode=defaultCode+"\n	            // Your code here!";
	defaultCode=defaultCode+"\n	            Scanner in = new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            String line=in.nextLine();";
	defaultCode=defaultCode+"\n	            String[] numsstring=line.split(\"[ ]+\");";
	defaultCode=defaultCode+"\n	            int hand []=new int[numsstring.length];";
	defaultCode=defaultCode+"\n	            int count=0;";
	defaultCode=defaultCode+"\n	            for(String s:numsstring){";
	defaultCode=defaultCode+"\n	            	hand [count++]=Integer.parseInt(s);";
	defaultCode=defaultCode+"\n	            }";
	defaultCode=defaultCode+"\n	            Scanner scan = new Scanner(System.in);";
	defaultCode=defaultCode+"\n	            int w = scan.nextInt();";
	defaultCode=defaultCode+"\n	            boolean result=isNStraightHand(hand ,w);";
	defaultCode=defaultCode+"\n	            System.out.println(result);";
	defaultCode=defaultCode+"\n	       ";
	defaultCode=defaultCode+"\n	      }";
	defaultCode=defaultCode+"\n	}";
	editor.setValue(defaultCode);
	editor.getSelection().clearSelection();
</script>	